spring:
  profiles:
    active: development
  application:
    name: Otp-Service
     
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Otp
        
thread:
  pool:
    core-pool-size: 10
    maximum-size: 20
    keep-alive: 60
    queue-pool-size: 100
    thread-name-prefix: UserService-Thread
      

server:
  port: 1010
---

spring:
  config:
    activate:
      on-profile: development
         
  jpa:
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: mohdsharif559@gmail.com
    password: tgsemecplworufjm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

spring:
  config:
    activate:
      on-profile: production

  jpa:
    show-sql: false