spring:
  profiles:
    active: development
  application:
    name: User-Service
     
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_database
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update 
        
thread:
  pool:
    core-pool-size: 10
    maximum-size: 20
    keep-alive: 60
    queue-pool-size: 100
    thread-name-prefix: UserService-Thread
      

server:
  port: 4046
---

spring:
  config:
    activate:
      on-profile: development
         
  jpa:
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: mohdsharif559@gmail.com
    password: tgsemecplworufjm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

spring:
  config:
    activate:
      on-profile: production

  jpa:
    show-sql: false